spring:
  application:
    name: inventory-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/inventory_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Kuna@1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 1919

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1918/eureka}
    fetchRegistry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true